# include: package:lint/analysis_options.yaml
include: package:flutter_lints/flutter.yaml

analyzer:
  exclude:
    # ignore warnings in generated files
    - "**/*.g.dart"
    - "**/*.freezed.dart"
  errors:
    missing_required_param: error
    missing_return: error
    must_be_immutable: error
    must_call_super: error
    invalid_use_of_protected_member: error
    parameter_assignments: error
    argument_type_not_assignable: ignore
    sort_unnamed_constructors_first: ignore
    sort_pub_dependencies: ignore
  strong-mode:
    implicit-casts: false
    # implicit-dynamic: false