name: interviewer_quiz_flutter_app
description: A new Flutter application.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.13.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  # H_ essential
  json_annotation: ^4.1.0
  path_provider: ^2.0.2
  freezed_annotation: ^0.14.3
  uuid: ^3.0.4
  collection: ^1.15.0
  supercharged: ^2.0.0
  # H_ log
  logger: ^1.0.0
  stack_trace: ^1.10.0
  path: ^1.8.0
  # H_ get_it
  get_it: ^7.1.3
  injectable: ^1.5.0
  # H_ bloc
  flutter_bloc: ^7.1.0
  hydrated_bloc: ^7.0.1
  flutter_hooks_bloc: ^0.15.0+1
  # H_ database
  hive: ^2.0.4
  hive_flutter: ^1.1.0
  synchronized: ^3.0.0
  # H_ firebase
  firebase_core: ^1.6.0
  cloud_firestore: ^2.5.1
  firebase_storage: ^10.0.3
  # H_ network
  connectivity_plus: ^1.0.6
  # H_ recorder
  flutter_sound_lite: ^8.3.9
  permission_handler: ^8.1.4+2
  # H_ route
  # FIXME 有問題，先直接改 package local 程式碼
  #  https://github.com/Milad-Akarie/auto_route_library/issues/659#issuecomment-906828351
  auto_route: ^2.3.0
  # H_ widget/presentation
  sizer: ^2.0.13
  responsive_framework: ^0.1.4
  flutter_hooks: ^0.18.0
  # flutter_staggered_grid_view: ^0.4.0
  flutter_keyboard_visibility: ^5.0.3
  # sliver_tools: ^0.2.5
  # material_floating_search_bar: ^0.3.4
  # scrollable_positioned_list: ^0.2.0-nullsafety.0
  # scrollable_positioned_list:
  #   git:
  #     url: https://github.com/lvfen/flutter.widgets.git
  #     ref: shrinkWrapSupport
  #     path: packages/scrollable_positioned_list
  # FIXME 從 git 匯入會出現奇怪的問題，先用 local 解決
  scrollable_positioned_list:
    path: C://Users/z/AndroidStudioProjects/flutter.widgets/packages/scrollable_positioned_list
  flash: ^2.0.1
  # H_ others
  dartz: ^0.10.0
  # kt_dart: ^0.9.1
  tuple: ^2.0.0
  rxdart: ^0.27.0
  expression_language: ^1.0.1
  # isolate: ^2.1.1
  async_task: ^1.0.11

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner:
  # H_ essential
  json_serializable: ^5.0.0
  freezed: ^0.14.5
  # H_ get_it
  injectable_generator: ^1.4.1
  # H_ route
  auto_route_generator: ^2.3.0
  # H_ lint
  # lint: ^1.5.3
  flutter_lints: ^1.0.4

flutter:
  uses-material-design: true

  assets:
     - assets/interviewer_list.json

  fonts:
    - family: NotoSansTC
      fonts:
        - asset: fonts/NotoSansTC-Thin.otf
          weight: 100
        - asset: fonts/NotoSansTC-Light.otf
          weight: 300
        - asset: fonts/NotoSansTC-Regular.otf
          weight: 400
        - asset: fonts/NotoSansTC-Medium.otf
          weight: 500
        - asset: fonts/NotoSansTC-Bold.otf
          weight: 700
        - asset: fonts/NotoSansTC-Black.otf
          weight: 900
